###############################################################################
DEFAULT_BENTHIC_PLOT_OPTIONS = {
    "figsize": (10, 10),
    "projection": "PlateCarree",
    "contour_levels": 26,
    "cmap": "jet",
    "contour_extend": "both",
    "coastline_linewidth": 1.5,
    "borders_linestyle": ":",
    "gridline_color": "gray",
    "gridline_linestyle": "--",
    "grid_draw_labels": True,
    "grid_dms": True,
    "grid_x_inline": False,
    "grid_y_inline": False,
    "colorbar_width": 0.65,
    "colorbar_height": 0.025,
    "colorbar_left": None,  # This must exist in the dictionary!
    "colorbar_bottom": 0.175,
    "colorbar_label": "[m]",
    "colorbar_labelsize": 12,
    "colorbar_tick_length": 18,
    "colorbar_ticklabelsize": 10,
    "colorbar_ticks": None,
    "spine_linewidth": 2,
    "spine_edgecolor": "black",
    "title": "Benthic Layer Depth",
    "title_fontsize": 16,
    "title_fontweight": "bold",
    "dpi": 150,
    "filename": "NA - Benthic Depth.png",
}
###############################################################################

###############################################################################
DEFAULT_BENTHIC_PHYSICAL_PLOT_OPTIONS = {
    "bfm2plot": "votemper",
    "unit": "°C",
    "description": "Bottom Temperature",
    "output_path": "output",
    "figsize": (10, 10),
    "cmap_jet": "jet",
    "cmap_jet_r": "jet_r",
    "vmin_votemper": 5,
    "vmax_votemper": 25,
    "vmin_vosaline": 36,
    "vmax_vosaline": 39,
    "vmin_density": 1025,
    "vmax_density": 1030,
    "num_ticks_votemper": 5,
    "num_ticks_vosaline": 7,
    "num_ticks_density": 6,
    "levels_votemper": 41,
    "levels_vosaline": 41,
    "levels_density": 51,
    "colorbar_position": [0.175, 0.175, 0.65, 0.025],
    "colorbar_labelsize": 14,
    "colorbar_tick_length": 18,
    "colorbar_tick_labelsize": 10,
    "coastline_linewidth": 2,
    "border_linestyle": ":",
    "gridline_color": "gray",
    "gridline_linestyle": "--",
    "title_fontsize": 16,
    "title_fontweight": "bold",
    "dpi": 150,
}
###############################################################################

###############################################################################
DEFAULT_BENTHIC_CHEMICAL_PLOT_OPTIONS = {
    "bfm2plot": "",
    "unit": "",
    "description": "",
    "output_path": "output",
    "epsilon": 0.06,
    "figsize": (10, 10),
    "dpi": 150,
    "coastline_linewidth": 2,
    "border_linestyle": ":",
    "gridline_color": "gray",
    "gridline_linestyle": "--",
    "title_fontsize": 16,
    "title_fontweight": "bold",
    "colorbar_position": [0.175, 0.175, 0.65, 0.025],
    "colorbar_labelsize": 14,
    "colorbar_tick_length": 18,
    "colorbar_tick_labelsize": 10,
    "spine_linewidth": 2,
    "spine_edgecolor": "black",
}
###############################################################################